
#+title: Muh Dotfiles
#+author: Aksel Olav Steen
#+options: toc:nil

* Introduction
  This are my dotfiles, there are many like them, but these are mine. My
  dotfiles is my best friend. It is my life. \\
  
  Hosts are split into 3 categories:
  - [[./hosts/sinnoh/README.org][Sinnoh]]: Arch/Arch-like systems
    + Usernames: Gen IV pokemon
  - [[./hosts/kalos/README.org][Kalos]]: Darwin systems
    * Usernames: Gen VI pokemon
  - [[./hosts/johto/README.org][Johto]]: NixOS systems
    * Usernames: Gen II pokemon

   

* Steps to install

  1. Install Nix
    #+begin_src sh
    sh <(curl -L https://nixos.org/nix/install)
    #+end_src

  2. Clone this repo
    #+begin_src sh
    git clone --recurse-submodules https://github.com/aksel-os/.dotfiles.git    
    #+end_src

    =--recurse-submodules= will also clone my emacs repo.

  3. cd into =.dotfiles=
   #+begin_src sh
   cd ~/.dotfiles/
   #+end_src

  4. Change placeholders in =flake.nix= and =.envrc=
   #+begin_src sh
   sed -i '' -e 's/ARCHITECTURE/your_architecture/g' -e 's/HOSTNAME/your_hostname/g' -e 's/USERNAME/your_username/g' flake.nix
   sed -i '' -e 's/USERNAME/your_username/g' -e 's/HOSTNAME/your_hostname/g' .envrc
   #+end_src

   Note: mac requires and empty string for =-i=, if you're on linux you should
   remove the empty string

  5. Build the flake
    #+begin_src sh    
    make system arg=nixos or darwin
    make home TRAINER_USER_PROFILE="your_username"
    #+end_src
* Updating

After making any changes to the user level modules, run
#+begin_src sh
make home
#+end_src

Changes at the system level will require you to run
#+begin_src sh
make system arg=nixos or darwin
#+end_src

* Future plans
Make a cli like GUIX to manage things. Inspired by librephenix and hlissner's dotfiles
