#+title: Muh Dotfiles
#+author: Aksel Olav Steen
#+options: toc:nil

* Introduction
  This are my dotfiles, there are many like them, but these are mine. My
  dotfiles is my best friend. It is my life. \\

  Current users:
  - Kepler: Darwin systems
  - Aether: Linux systems
  - Misdreavus: Linux VM

  Current hosts:
  - Cygnus: Macbook Pro M1
  - Ophicus: Thinkbook E490
  - [[./hosts/johto/README.org][Johto]]: NixOS VM


* Steps to install
  1. Install Nix
    #+begin_src sh
    sh <(curl --proto '=https' --tlsv1.2 -L https://nixos.org/nix/install) --daemon
    #+end_src

  2. Clone this repo
    #+begin_src sh
    git clone git@github.com:aksel-os/.dotfiles
        
    # or

    git clone https://github.com/aksel-os/.dotfiles.git    
    #+end_src

  3. cd into =.dotfiles=
   #+begin_src sh
   cd ~/.dotfiles/
   #+end_src

  4. Build the flake
    #+begin_src sh
    nix develop

    # mac
    just provision

    # linux
    just setup  
    #+end_src

** Installing on NixOS
   Assuming you've cloned the directory.

   1. Format the drive NixOS will be installed on
      #+begin_src sh
      nix --experimental-features "nix-command flakes" run
      github:nix-community/disko/latest -- --mode destroy,format,mount path/to/disko/config
#+end_src

   2. Remove any mentions to my secrets flake. As this will cause the build to
      fail.
   
   3. Run the nixos-install command targeting the flake and correct host
      #+begin_src sh
      nixos-install --flake /absolute/path/to/flake.nix.#<host>
      #+end_src

   4. Add your own secrets, and rebuild the flake afterwards to apply the
      changes.
      #+begin_src sh
      just switch
      #+end_src
   
    
* Updating
  To apply changes made to the =./modules=, =./homes= or =./hosts=, run the following:
  #+begin_src sh
  just switch
  #+end_src

  To update the flake.lock run the following:
  #+begin_src sh
  just update

  # or

  just update <pkg>
  #+end_src

